In [1]:
import numpy as np

In [2]:
np.random.seed(1234)

In [3]:
sizes = [2, 3, 1]

In [4]:
biases = [np.random.randn(layer_size, 1) for layer_size in sizes[1:]]

In [6]:
zip(sizes[:-1], sizes[1:])

[(2, 3), (3, 1)]

In [13]:
weights = []
for x, y in zip(sizes[:-1], sizes[1:]):
    print x, y
    a = np.random.randn(y, x)
    print a
    weights.append(a)
    print '\n'

2 3
[[ 0.19342138  0.55343891]
 [ 1.31815155 -0.46930528]
 [ 0.67555409 -1.81702723]]


3 1
[[-0.18310854  1.05896919 -0.39784023]]




In [12]:
weights[0]

array([[-2.02125482, -0.33407737],
       [ 0.00211836,  0.40545341],
       [ 0.28909194,  1.32115819]])

In [10]:
weights[1]

array([[1.15003572],
       [0.99194602],
       [0.95332413]])

In [15]:
biases[0]

array([[ 0.47143516],
       [-1.19097569],
       [ 1.43270697]])

In [16]:
biases[1]

array([[-0.3126519]])